/*
 * Generated by ISE 15.08.9.7862 GPL Edition - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F914_17591();
extern void F916_17744();
extern void F924_17833();
extern void F926_17994();
extern void F1561_10526();
extern void F1551_16958();
extern void F347_6516();
extern EIF_REFERENCE F347_6503();
extern EIF_BOOLEAN F347_6515();
extern EIF_BOOLEAN F347_6520();
extern void F347_6525();
extern void F347_6526();
extern void F347_6527();
extern void F368_6688();
extern EIF_TYPED_VALUE F368_6689();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F914_17591;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F924_17833;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F1561_10526;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F916_17744;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F926_17994;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F1551_16958;
					#ifdef RTS_SCP_CAPABLE
						egc_is_scoop_capable = 0;
					#endif
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F347_6516;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F347_6515;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F347_6503;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F347_6520;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F347_6525;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F347_6526;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F347_6527;

	egc_str_dtype = 915;

	egc_str32_dtype = 925;
	egc_arr_dtype = 1560;
	egc_tup_dtype = 841;
	egc_disp_rout_id = 10953;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x0718;
	egc_sp_wchar = 0x07DA;
	egc_sp_bool = 0x07A1;
	egc_sp_uint8 = 0x0680;
	egc_sp_uint16 = 0x083C;
	egc_sp_uint32 = 0x077A;
	egc_sp_uint64 = 0x073C;
	egc_sp_int8 = 0x06C1;
	egc_sp_int16 = 0x071B;
	egc_sp_int32 = 0x0646;
	egc_sp_int64 = 0x0859;
	egc_sp_real32 = 0x068E;
	egc_sp_real64 = 0x06DF;
	egc_sp_pointer = 0x0780;
	egc_sp_ref = 0x060C;

	egc_uint8_dtype = 876;
	egc_uint16_dtype = 855;
	egc_uint32_dtype = 852;
	egc_uint64_dtype = 861;
	egc_int8_dtype = 846;
	egc_int16_dtype = 879;
	egc_int32_dtype = 870;
	egc_int64_dtype = 849;
	egc_bool_dtype = 867;
	egc_real32_dtype = 858;
	egc_char_dtype = 873;
	egc_wchar_dtype = 843;
	egc_real64_dtype = 864;
	egc_point_dtype = 882;

	egc_exception_dtype = 489;
	egc_except_emnger_dtype = 346;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "assignment_4";
	egc_system_location = "C:\\Users\\Tom\\Documents\\Eiffel Workspace\\traffic\\examples\\assignment_4\\EIFGENs\\assignment_4\\W_code";
	egc_compiler_tag = 38;
	egc_project_version = 1442503397;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 2606;

	egc_rcount = 1;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "APPLICATION.execute";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 25777;
	egc_rcarg[0] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 367;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F368_6688;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F368_6689;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 2355; /* APPLICATION */
	}
}

#ifdef __cplusplus
}
#endif
